.PHONY: clean All

All:
	@echo "----------Building project:[ day6 - Debug ]----------"
	@cd "day6" && "$(MAKE)" -f  "day6.mk"
clean:
	@echo "----------Cleaning project:[ day6 - Debug ]----------"
	@cd "day6" && "$(MAKE)" -f  "day6.mk" clean
