.PHONY: clean All

All:
	@echo "----------Building project:[ day7alex - Debug ]----------"
	@cd "day7alex" && "$(MAKE)" -f  "day7alex.mk"
clean:
	@echo "----------Cleaning project:[ day7alex - Debug ]----------"
	@cd "day7alex" && "$(MAKE)" -f  "day7alex.mk" clean
