.PHONY: clean All

All:
	@echo "----------Building project:[ day7 - Debug ]----------"
	@cd "day7" && "$(MAKE)" -f  "day7.mk"
clean:
	@echo "----------Cleaning project:[ day7 - Debug ]----------"
	@cd "day7" && "$(MAKE)" -f  "day7.mk" clean
